"use client"; // 👈 Required for useSession to work

import { SessionProvider } from "next-auth/react";
// import type { Metadata } from "next";
import "../global/globals.css";
import Header from "../components/Headder/Header";
import Footer from "../components/Footer/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider> {/* ✅ Wrap entire app with SessionProvider */}
          <Header />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
